// TODOS:
// 1. Put getTasks and strikeTasks in separate files
// 2. Refactoring: 
    // This works by modifying the DOM object itself, but the change 
    // doesn't persist when a new task is added and the DOM is 
    // regenerated by the displayList function.
    // 
    // It would probably be better to modify the done status of the 
    // task objects in the task list and regenerate the DOM with 
    // displayList, where the apparence is controled by the status of 
    // the task object in the list.

function getTasks(cssClass) {
    let paras = document.querySelectorAll(cssClass);  // For some reason, this is returning an empty node list
    return paras;
}

function strikeTasks(tasks) {
    tasks.forEach(task => {
        task.addEventListener("click", crossOut, false);
        // task.checked = true;  // this is causing the item to be cross-out immediatedly; see library project for similar issue
    });
}

function crossOut(e) {
    console.log("Cross out this item.")
    e.target.classList.toggle("checked-item");
}

export { getTasks, strikeTasks };